# -*- coding: utf-8 -*-
"""ner_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHaq9QgCARPiKSeYRF4bqs5bqGk1aJCC
"""

import torch
from transformers import RobertaTokenizerFast, RobertaForTokenClassification

tag2id = {"O": 0, "B-ANIMAL": 1, "I-ANIMAL": 2}
id2tag = {v: k for k, v in tag2id.items()}

def load_model_and_tokenizer(weights_path, tokenizer_dir):
    tokenizer = RobertaTokenizerFast.from_pretrained(tokenizer_dir)
    model = RobertaForTokenClassification.from_pretrained("roberta-base", num_labels=len(tag2id))
    state_dict = torch.load(weights_path, map_location=torch.device("cpu"))
    model.load_state_dict(state_dict)
    model.eval()
    return model, tokenizer

def predict(model, tokenizer, sentence):
    tokens = sentence.split()
    encoding = tokenizer(tokens, is_split_into_words=True, return_tensors="pt", add_special_tokens=True,
                         truncation=True, padding="max_length", max_length=64)
    word_ids = encoding.word_ids(batch_index=0)

    with torch.no_grad():
        outputs = model(**encoding)

    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1).squeeze().tolist()

    previous_word_idx = None
    labels = []
    for idx, word_idx in enumerate(word_ids):
        if word_idx is None:
            continue
        if word_idx != previous_word_idx:
            labels.append(id2tag[predictions[idx]])
        previous_word_idx = word_idx

    return list(zip(tokens, labels))