# -*- coding: utf-8 -*-
"""train_ner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2GTmH0fTreOXnqWW3cOJC9CYtETOWFc
"""

# generate train data for NER
train_data = [
    {"tokens": ["There", "is", "a", "dog", "in", "the", "park", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["I", "see", "a", "cat", "and", "a", "cow", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["Look", "at", "the", "elephant", "and", "the", "butterfly", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["The", "dogs", "are", "playing", "in", "the", "yard", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["Several", "cats", "were", "seen", "near", "the", "barn", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["Horses", "run", "fast", "across", "the", "field", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["The", "elephants", "trumpeted", "loudly", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Butterflies", "fluttered", "around", "the", "garden", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["Chickens", "are", "laying", "eggs", "in", "the", "coop", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["The", "spiders", "built", "webs", "between", "the", "trees", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["Cows", "grazed", "in", "the", "meadow", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["Sheep", "are", "herded", "by", "the", "shepherd", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["Squirrels", "climbed", "up", "the", "trees", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["A", "dog", "and", "a", "cat", "are", "friends", "."], "tags": ["O", "B-ANIMAL", "O", "O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Two", "horses", "galloped", "across", "the", "field", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["I", "saw", "an", "elephant", "near", "the", "river", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Butterfly", "wings", "are", "colorful", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["The", "chicken", "crossed", "the", "road", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["A", "spider", "spun", "its", "web", "quickly", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["Cow", "milk", "is", "fresh", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["A", "sheep", "was", "grazing", "in", "the", "field", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O", "O"]},
    {"tokens": ["The", "squirrel", "is", "fast", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Dogs", "and", "cats", "live", "together", "sometimes", "."], "tags": ["B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["I", "found", "a", "cow", "and", "a", "sheep", "in", "the", "field", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Butterflies", "and", "spiders", "inhabit", "the", "garden", "."], "tags": ["B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Dog", "barks", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Cat", "sleeps", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Horse", "runs", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Elephant", "trumpets", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Butterfly", "flies", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Chicken", "clucks", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Spider", "creeps", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Cow", "moos", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Sheep", "bleats", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["Squirrel", "scampers", "."], "tags": ["B-ANIMAL", "O", "O"]},
    {"tokens": ["The", "big", "dog", "runs", "fast", "."], "tags": ["O", "O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["A", "small", "cat", "is", "sleeping", "."], "tags": ["O", "O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Two", "young", "horses", "galloped", "."], "tags": ["O", "O", "B-ANIMAL", "O", "O"]},
    {"tokens": ["The", "gray", "elephant", "walks", "slowly", "."], "tags": ["O", "O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Several", "dogs", "and", "cats", "are", "playing", "outside", "."], "tags": ["O", "B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["The", "horses", "and", "elephants", "share", "the", "field", "."], "tags": ["O", "B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Butterflies", "and", "chickens", "are", "common", "in", "the", "farm", "."], "tags": ["B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["There", "is", "no", "dog", "here", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O"]},
    {"tokens": ["I", "don't", "see", "any", "cats", "around", "."], "tags": ["O", "O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["No", "horses", "were", "found", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Is", "there", "a", "dog", "in", "the", "yard", "?"], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Are", "cats", "playing", "outside", "?"], "tags": ["O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Where", "is", "the", "elephant", "?"], "tags": ["O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["Dog,", "cat,", "and", "cow", "are", "animals", "."], "tags": ["B-ANIMAL", "O", "O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["I", "love", "my", "Dog", "and", "Horse", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "B-ANIMAL", "O"]},
    {"tokens": ["The", "cowboy", "rode", "a", "horse", "."], "tags": ["O", "O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["Butterfly", "wingspan", "is", "wide", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["My", "cat", "is", "sleeping", "on", "the", "couch", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["The", "dog", "barked", "loudly", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O"]},
    {"tokens": ["Several", "sheep", "were", "grazing", "in", "the", "field", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["That", "dog", "is", "very", "friendly", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["A", "flock", "of", "sheep", "ran", "away", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O", "O"]},
    {"tokens": ["The", "spider", "crept", "silently", "on", "the", "wall", "."], "tags": ["O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
    {"tokens": ["Show", "me", "the", "dog", "."], "tags": ["O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["Where", "is", "the", "cat", "?"], "tags": ["O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["My", "favorite", "animal", "is", "the", "elephant", "."], "tags": ["O", "O", "O", "O", "O", "B-ANIMAL", "O"]},
    {"tokens": ["Elephants", "are", "large", "animals", "."], "tags": ["B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Cats", "and", "dogs", "are", "common", "pets", "."], "tags": ["B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O"]},
    {"tokens": ["Chickens", "and", "spiders", "can", "be", "found", "in", "barns", "."], "tags": ["B-ANIMAL", "O", "B-ANIMAL", "O", "O", "O", "O", "O"]},
]

import torch
from google.colab import files
from torch.utils.data import Dataset, DataLoader
from transformers import (
    RobertaTokenizerFast,
    RobertaForTokenClassification,
    get_scheduler,
)
from torch.optim import AdamW
from tqdm import tqdm
import shutil

# Define tag mappings
tag2id = {"O": 0, "B-ANIMAL": 1, "I-ANIMAL": 2}
id2tag = {v: k for k, v in tag2id.items()}

class AnimalNERDataset(Dataset):
    def __init__(self, data, tokenizer, tag2id, max_length=64):
        self.tokenizer = tokenizer
        self.tag2id = tag2id
        self.max_length = max_length
        self.encodings = []
        self.labels = []

        for item in data:
            tokens = item["tokens"]
            tags = item["tags"]

            encoding = tokenizer(
                tokens,
                is_split_into_words=True,
                truncation=True,
                padding="max_length",
                max_length=self.max_length,
                return_tensors="pt",
                add_special_tokens=True,
            )

            word_ids = encoding.word_ids(batch_index=0)
            label_ids = []
            previous_word_idx = None

            for word_idx in word_ids:
                if word_idx is None or word_idx >= len(tags):
                    label_ids.append(-100)  # ignore special tokens or out-of-range
                elif word_idx != previous_word_idx:
                    label_ids.append(tag2id[tags[word_idx]])
                else:
                    if tags[word_idx].startswith("B-"):
                        label_ids.append(tag2id["I-ANIMAL"])
                    else:
                        label_ids.append(tag2id[tags[word_idx]])
                previous_word_idx = word_idx

            self.encodings.append(encoding)
            self.labels.append(torch.tensor(label_ids))

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val.squeeze() for key, val in self.encodings[idx].items()}
        item["labels"] = self.labels[idx]
        return item


def train():
    tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base", add_prefix_space=True)
    model = RobertaForTokenClassification.from_pretrained(
        "roberta-base", num_labels=len(tag2id)
    )

    dataset = AnimalNERDataset(train_data, tokenizer, tag2id)
    dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

    optimizer = AdamW(model.parameters(), lr=5e-5)
    num_epochs = 3
    num_training_steps = num_epochs * len(dataloader)

    lr_scheduler = get_scheduler(
        "linear", optimizer=optimizer, num_warmup_steps=0, num_training_steps=num_training_steps
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.train()

    for epoch in range(num_epochs):
        loop = tqdm(dataloader, leave=True)
        total_loss = 0
        for batch in loop:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)
            loss = outputs.loss
            loss.backward()

            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

            total_loss += loss.item()
            loop.set_description(f"Epoch {epoch + 1}")
            loop.set_postfix(loss=loss.item())

        print(f"Epoch {epoch + 1} average loss: {total_loss / len(dataloader):.4f}")

    # Save files
    torch.save(model.state_dict(), "ner_model_weights.pth")
    tokenizer.save_pretrained("ner_tokenizer")
    # download files locally
    files.download("ner_model_weights.pth")
    shutil.make_archive("ner_tokenizer", 'zip', "ner_tokenizer")
    files.download("ner_tokenizer.zip")

    print("Training complete! Weights saved to ner_model_weights.pth")
    print("Tokenizer saved to ner_tokenizer/ directory")


if __name__ == "__main__":
    train()