# -*- coding: utf-8 -*-
"""inference_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUxuJfV3oVymCQyPrw5T9d9UWVHhfuKF
"""

import torch
from torchvision import models, transforms
from PIL import Image

class_names_en = ["dog", "cat", "horse", "elephant", "butterfly", "chicken", "spider", "cow", "sheep", "squirrel"]

# load model
def load_model(model_path):
    model = models.resnet18(pretrained=False)
    model.fc = torch.nn.Linear(model.fc.in_features, len(class_names_en))
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
    model.eval()
    return model

# preprocess the image (same as training!)
def preprocess_image(image_path):
    transform = transforms.Compose([  # ← FIXED
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])
    img = Image.open(image_path).convert("RGB")
    return transform(img).unsqueeze(0)  # batch dimension was handled by dataloader in training

# predict class from image
def predict(model, input_tensor):
    with torch.no_grad():
        output = model(input_tensor)
        pred_idx = output.argmax(dim=1).item() #class index that has highest score
    return class_names_en[pred_idx]