# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9WA9UgImlNkyJ0RwxK91kZB-D1M3pMP
"""

import os
import kagglehub
import torch
from torch import nn, optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from tqdm import tqdm
from google.colab import files

def main():
    path = kagglehub.dataset_download("alessiocorrado99/animals10")
    data_path = os.path.join(path, "raw-img")

    # Italian → English translation
    translate = {
        "cane": "dog", "gatto": "cat", "cavallo": "horse", "elefante": "elephant",
        "farfalla": "butterfly", "gallina": "chicken", "ragno": "spider",
        "mucca": "cow", "pecora": "sheep", "scoiattolo": "squirrel"
    }

    # transformations
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])

    dataset = datasets.ImageFolder(root=data_path, transform=transform)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

    # sorted class names
    it_classes_sorted = sorted(dataset.class_to_idx.items(), key=lambda x: x[1])
    class_names_en = [translate[it] for it, _ in it_classes_sorted]

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = models.resnet18(pretrained=True)
    model.fc = nn.Linear(model.fc.in_features, len(class_names_en))
    model = model.to(device)

    # loss and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-4)

    # train model
    epochs = 10
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        for images, labels in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1} average loss: {total_loss / len(dataloader):.4f}")

    # save
    os.makedirs("classifier", exist_ok=True)
    weights_path = "classifier/resnet18_animals10.pth"
    torch.save(model.state_dict(), weights_path)

    files.download(weights_path)

if __name__ == "__main__":
    main()