# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9WA9UgImlNkyJ0RwxK91kZB-D1M3pMP
"""

import os
import kagglehub
import torch
from torch import nn, optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from tqdm import tqdm

def main():
    path = kagglehub.dataset_download("alessiocorrado99/animals10")
    data_path = os.path.join(path, "raw-img")

    # Italian to English translation of animal names
    translate = {
        "cane": "dog", "gatto": "cat", "cavallo": "horse", "elefante": "elephant",
        "farfalla": "butterfly", "gallina": "chicken", "ragno": "spider",
        "mucca": "cow", "pecora": "sheep", "scoiattolo": "squirrel"
    }

    # transformations
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])

    dataset = datasets.ImageFolder(root=data_path, transform=transform)
    dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

    class_names_it = dataset.classes
    class_names_en = [translate[name] for name in class_names_it]

    print("Classes (IT):", class_names_it)
    print("Classes (EN):", class_names_en)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print("Using device:", device)

    # pretrained model Resnet18
    model = models.resnet18(pretrained=True)
    model.fc = nn.Linear(model.fc.in_features, len(class_names_en))
    model = model.to(device)

    # loss and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    # training
    epochs = 5
    for epoch in range(epochs):
        model.train()
        running_loss = 0.0 #variable to calculate loss
        for images, labels in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad() #resets gradient from previous batch
            outputs = model(images) #images go through the model
            loss = criterion(outputs, labels) #compares predicted outputs and labels we have
            loss.backward() #backpropagation
            optimizer.step() #update model

            running_loss += loss.item()
        avg_loss = running_loss / len(dataloader)
        print(f"Loss after epoch {epoch+1}: {avg_loss:.4f}")

    os.makedirs("classifier", exist_ok=True)
    # save model weights
    torch.save(model.state_dict(), "classifier/resnet18_animals10.pth")

    # download saved weights file locally
    files.download("classifier/resnet18_animals10.pth")

if __name__ == "__main__":
    main()

