# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9WA9UgImlNkyJ0RwxK91kZB-D1M3pMP
"""

import os
import kagglehub
import torch
from torch import nn, optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from tqdm import tqdm
from google.colab import files
from PIL import Image
import torch.nn.functional as F
import matplotlib.pyplot as plt
from google.colab import files

def main():
    path = kagglehub.dataset_download("alessiocorrado99/animals10")
    data_path = os.path.join(path, "raw-img")

    # Italian → English translation
    translate = {
        "cane": "dog", "gatto": "cat", "cavallo": "horse", "elefante": "elephant",
        "farfalla": "butterfly", "gallina": "chicken", "ragno": "spider",
        "mucca": "cow", "pecora": "sheep", "scoiattolo": "squirrel"
    }

    # transformations
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])

    dataset = datasets.ImageFolder(root=data_path, transform=transform)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

    # sorted class names to match dataset.class_to_idx order
    it_classes_sorted = sorted(dataset.class_to_idx.items(), key=lambda x: x[1])
    class_names_en = [translate[it] for it, _ in it_classes_sorted]
    print("Class names (English) in order:", class_names_en)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = models.resnet18(pretrained=True)
    model.fc = nn.Linear(model.fc.in_features, len(class_names_en))
    model = model.to(device)

    # loss and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-4)

    # train model
    epochs = 10
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        for images, labels in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1} average loss: {total_loss / len(dataloader):.4f}")

    # save model weights
    os.makedirs("classifier", exist_ok=True)
    weights_path = "classifier/resnet18_animals10.pth"
    torch.save(model.state_dict(), weights_path)

    files.download(weights_path)

    # return model and class names for immediate prediction use
    return model, class_names_en, transform, device

# testing model
model, class_names_en, transform, device = main()
model.eval()
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
image = Image.open(image_path).convert('RGB')
image_tensor = transform(image).unsqueeze(0).to(device)
with torch.no_grad():
    outputs = model(image_tensor)
    probabilities = F.softmax(outputs[0], dim=0)
    predicted_idx = torch.argmax(probabilities).item()
    predicted_label = class_names_en[predicted_idx]
    confidence = probabilities[predicted_idx].item()

print(f"Predicted class: {predicted_label} (confidence: {confidence:.4f})")

plt.imshow(image)
plt.title(f"Prediction: {predicted_label} ({confidence*100:.1f}%)")
plt.axis('off')
plt.show()